### ISSUE TITLE
Mousewheel zoom seems to be malfunctioning... just acting as a toggle between 2 sizes

### ISSUE THREAD

**Issue by luckman212** [johansan/pixel-perfect-image#7]
A bit hard to describe this bug, which is occurring on my MacBook Air M2 (trackpad, using standard 2-finger gesture as "scroll")

I have tried different options for Zoom step (20%, 10%, 5% etc) which has no effect on the bug.

The modifier keypress seems to get detected TWICE (see repeat message logged to console for each press and release) — not sure if that is related.

Holding the modifier and activating the scroll causes the underlying image to zoom to a very large size, and then scrolling the other direction changes it to another also very large size. It just bounces between these 2 odd sizes, it does not allow smooth resizing to other dimensions.

Here's a screen recording...

https://github.com/user-attachments/assets/c5ae80f5-0b66-42df-aadc-c65e44b8e920

Obsidian 1.8.7, macOS 15.3.1

**Comment by johansan** [comment]
Thanks. it's optimized for mouse wheel scroll now, I will look into trackpad scrolling shortly.

**Comment by luckman212** [comment]
Just a comment: I have another Mac with a scroll-wheel mouse (a venerable [Microsoft Wheel Mouse Optical](https://www.newegg.com/microsoft-d66-00066/p/N82E16826105185)) and it behaves the same way. Instead of resizing smoothly, it just jolts / locks, essentially toggling between 2 very large sizes.

Not sure how I can assist with debugging this.

**Comment by johansan** [comment]
No worries I know what's wrong, it's when they send a continuous stream of resize events instead of just one event as a traditional click-scroll-wheel. I will look into it

**Comment by johansan** [comment]
Hi, I have published version 1.0.11 that works much better. Not 100% but better, please give it a try.

**Comment by luckman212** [comment]
Thank you for trying, but I tried this version and it still does not work for me (using wheel mouse, have not even tried trackpad...). It still gets "stuck" where the image will only toggle between 2 very large sizes like 867—1123.
